[package]
name = "minimal-epub-reader"
version = "0.1.0"
description = "Minimal EPUB Reader"
authors = ["you"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "minimal_epub_reader_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
pulldown-cmark = "0.13"
epub = "2.1.5"
tauri-plugin-single-instance = "2"
katex-rs = "0.2"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
strip = true
